server:
  port: 8989
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      route:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: payment-service
        - uri: lb://payment-service
          predicates:
            - Path=/payment/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost